### ISSUE TITLE
getBalance script example 1 has the wrong input param

### ISSUE THREAD

**Issue by RedVelvetZip** [rsksmart/devportal#106]
Script example 1 (https://github.com/rsksmart/devportal/blob/42fdd270885a6fa472e12c0bd3db4b269bbb40b3/docs/02-developers/07-rpc-api/02-methods.md?plain=1#L208) claims to use a blockNumber for the second param, while example 2 claims to use a blockHash and example 3 claims to use a blockTag. Script examples 2 and 3 correctly use the params they claim to, but example 1 erroneously had a blockTag instead of a blockHash

**Comment by ivegabr** [comment]
thank you for your comment
